import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Weather from './components/Weather';

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${NEXT_PUBLIC_API}`;
  const fetchWeather = (e) => {
    e.preventDefault();
    axios.get(url).then((response) => {
      setWeather(response.data);
      // console.log(response.data);
    });
    setCity('');
  };

    return (
      <div>
        <Head>
          <title>Weather-App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
       
        <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/20 z-[-1]' />
        <Image
          src='https://images.unsplash.com/photo-1567190564513-6fb2fb610318?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80'
          layout='fill'
          className='object-cover'
        />

        <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
           {/*it is done so, input text does not change on entry of every character*/}
          <form
            onSubmit={fetchWeather} 
            className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'
          >
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                className='bg-transparent border-none text-white focus:outline-none text-2xl'
                type='text'
                placeholder='Search city'
              />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={20} />
            </button>
          </form>
        </div>
        {weather.main &&<Weather data={weather} />}
      </div>
    );
  }
